(function (global) {
  global.LANG_JA = {
    game_eyebrow: "かわいい前線司令室", game_title: "Tug of War TD", game_subtitle: "ねこ軍団とモンスターの綱引き", game_tagline: "召喚して、押して、お城を守ろう！",
    menu_start: "新しいゲーム", menu_continue: "続きから", menu_howto: "遊び方", menu_settings: "設定", menu_no_save: "続きの戦闘はありません", menu_continue_ready: "進行状況から続ける", menu_offline: "オフラインで遊べます", menu_autosave: "進行状況を自動保存", footer_local: "フロントエンドのみ・ダブルクリックで遊べる",
    level_eyebrow: "前線マップ", level_select: "ステージ選択", level_lead: "すべてのステージに挑戦できます。突破したい前線を選びましょう。", level_locked: "ロック中", level_unlocked: "解放済み", level_stars: "スター", level_unlimited: "無制限", level_play: "出撃", level_back: "戻る", difficulty_1: "新人訓練", difficulty_2: "小隊演習", difficulty_3: "前線激突", difficulty_4: "エース試練", difficulty_5: "城決戦", difficulty_6: "Boss強化戦",
    level_1_name: "いちご雲の丘", level_1_desc: "エネルギーと基本ユニットを覚える準備戦。", level_2_name: "青い潮の谷", level_2_desc: "遠距離の敵が登場。タンクで後衛を守りましょう。", level_3_name: "エメラルド森林線", level_3_desc: "属性が交差します。最適な反撃を見つけましょう。", level_4_name: "琥珀夕日の門", level_4_desc: "高圧の前線。突撃と回復の両方が大切です。", level_5_name: "月光の玉座", level_5_desc: "最後の決戦。柔軟な指揮で城を守り抜きましょう。", level_6_name: "王冠無限前線", level_6_desc: "強化戦：敵HPが10%減るたびに巨大Bossが出現します。",
    how_eyebrow: "新米司令官の手引き", how_title: "遊び方", how_tab_basic: "基本操作", how_tab_resource: "資源", how_tab_units: "ユニット図鑑", how_tab_matchup: "属性相性", how_tab_victory: "勝利条件", how_prev: "前へ", how_next: "次へ",
    how_basics_heading: "勝利の綱を引こう！", how_basics_intro: "同じ前線に部隊を送り、敵のお城を先に倒しましょう。", how_basic_1_title: "エネルギーを貯める", how_basic_1_desc: "時間で回復するエネルギーを見て、召喚のテンポを決めます。", how_basic_2_title: "ユニットを選ぶ", how_basic_2_desc: "下のカードをタップ。コスト、クールダウン、役割が異なります。", how_basic_3_title: "前線を押す", how_basic_3_desc: "ユニットは自動で進み戦います。司令官は派兵の判断をします。", how_basic_4_title: "基地を守る", how_basic_4_desc: "突破された敵は城を攻撃します。守りから反撃へ転じましょう。",
    how_resource_heading: "エネルギーがテンポを作る", how_resource_intro: "一度に使い切らず、低コストと高コストを組み合わせて前線を安定させます。", how_resource_1_title: "上限 100+", how_resource_1_desc: "ステージごとに上限と回復速度が違います。難しいほどテンポが速くなります。", how_resource_2_title: "賢く召喚", how_resource_2_desc: "カードの数字は召喚コスト。灰色のカードはエネルギー不足です。", how_resource_3_title: "クールダウン", how_resource_3_desc: "強いユニットは連続召喚できません。基本兵で隙間を埋めましょう。", how_resource_4_title: "押したら貯める", how_resource_4_desc: "敵を倒した後の余裕で次の攻撃に備えます。",
    how_units_heading: "部隊を知ろう", how_units_intro: "13種類の通常・特殊ユニットには役割があります。まず安定させ、好機に一気に攻めましょう。", how_matchup_heading: "属性相性", how_matchup_intro: "敵の色を確認。相性が良い属性は2倍のダメージを与えます。", how_victory_heading: "勝利ルール", how_victory_intro: "戦闘に時間制限はありません。城を破壊し、すべてのBossを倒し、自分の基地を守りましょう。",
    how_victory_1_title: "城を破壊", how_victory_1_desc: "敵の基地HPを0にし、すべてのBossを倒して初めて勝利です。自分の基地が0なら敗北です。", how_victory_2_title: "Bossを倒す", how_victory_2_desc: "生きているBossは敵の城を守ります。攻城を終える前にBossを倒しましょう。", how_victory_3_title: "スターを集める", how_victory_3_desc: "自分の城の残りHPで評価します。80%以上で3、45%以上で2、それ以外は1スターです。", how_victory_4_title: "全ステージ開放", how_victory_4_desc: "すべてのステージに直接挑戦でき、戦闘結果と進行状況は自動保存されます。",
    matchup_attacker: "攻撃側", matchup_effective: "有利", matchup_note: "効果", matchup_double: "ダメージ ×2", matchup_neutral: "安定・ボーナスなし", attribute_red: "赤", attribute_angel: "天使", attribute_demon: "悪魔", attribute_metal: "メタル", attribute_normal: "通常",
    settings_eyebrow: "司令室をカスタマイズ", settings_title: "設定", settings_audio: "オーディオ", settings_audio_hint: "リミッター付きの明るいサウンドで安全に楽しめます。", settings_bgm_volume: "音楽音量", settings_sfx_volume: "効果音音量", settings_sound_on: "サウンドオン", settings_sound_off: "ミュート中", settings_mute_hint: "すべての音を一度に停止", settings_theme: "カラーテーマ", settings_theme_hint: "今日守りたい空を選びましょう。", settings_language: "言語", settings_language_hint: "すぐに切り替え、設定は保存されます。", settings_data: "データ管理", settings_data_hint: "保存ステージと進行中の戦闘を消去します。", settings_clear_save: "セーブを消去", theme_cute: "キュートピンク", theme_ocean: "オーシャンブルー", theme_forest: "フォレストグリーン", theme_sunset: "サンセットオレンジ", theme_night: "ナイトモード", lang_zh: "中文", lang_en: "English", lang_ja: "日本語",
    battle_you: "自分の城", battle_enemy: "敵の城", battle_energy: "エネルギー", battle_energy_tip: "テンポを守ろう！", battle_lane_you: "ねこ前線", battle_lane_enemy: "モンスター前線", battle_summon: "部隊を召喚", battle_summon_hint: "カードをタップして前線へ送ろう", battle_cost: "コスト", battle_ready: "出撃可能", battle_cooldown: "クールダウン", battle_insufficient: "エネルギー不足", battle_spawned: "出撃！", battle_wave: "敵が来る！", battle_paused: "前線停止", battle_income_upgrade: "エネルギー強化", battle_upgrade_cost: "コスト", battle_upgrade_max: "最大LV5", battle_boss: "巨大Boss", battle_boss_warning: "Boss襲来！現在 {count}体", unit_attribute: "属性", unit_attack: "攻撃", unit_hp: "HP", unit_speed: "速度", unit_range: "射程",
    unit_basic_name: "基本兵", unit_basic_desc: "安くて頼れる前衛。数で押すのに最適です。", unit_ranger_name: "遠距離兵", unit_ranger_desc: "安全な後衛火力。ただしHPが低く守りが必要です。", unit_tank_name: "重装兵", unit_tank_desc: "厚い盾で前線をゆっくり押し上げます。", unit_striker_name: "突撃兵", unit_striker_desc: "高コスト・長クールダウンの強烈な一撃。", unit_healer_name: "ヒーラー", unit_healer_desc: "仲間を回復し前線を長く支えます。", unit_scout_name: "偵察兵", unit_scout_desc: "高速で前線を走る安価な先鋒です。", unit_guard_name: "守衛兵", unit_guard_desc: "中型の盾で前線の穴を埋めます。", unit_catapult_name: "投石兵", unit_catapult_desc: "遅いが強烈な長距離砲撃を行います。", unit_berserker_name: "バーサーカー", unit_berserker_desc: "HPが低いほど怒り、攻撃力が大きく上がります。", unit_frost_name: "氷魔導士", unit_frost_desc: "氷の攻撃で敵の移動速度を大きく下げます。", unit_thunder_name: "雷魔導士", unit_thunder_desc: "雷撃が近くの敵へ連鎖し、集団を倒します。", unit_guardian_name: "守護者", unit_guardian_desc: "近くの仲間にバリアを張り、ダメージを吸収します。", unit_summoner_name: "召喚士", unit_summoner_desc: "時間ごとに基本兵を無料召喚し、部隊を増やします。", unit_boss_name: "王冠Boss", unit_boss_desc: "城を守る巨大な敵。倒すまで攻城を続けられません。", unit_role_tank: "前衛", unit_role_ranged: "遠距離", unit_role_heavy: "タンク", unit_role_burst: "突撃", unit_role_support: "支援", unit_role_speed: "高速", unit_role_guard: "守衛", unit_role_siege: "攻城", unit_role_special: "特殊", unit_role_boss: "Boss", unit_ability_rage: "狂暴", unit_ability_frost: "氷結減速", unit_ability_chain: "連鎖雷撃", unit_ability_barrier: "バリア", unit_ability_summon: "無料召喚", attack_melee: "近接", attack_ranged: "遠距離", attack_support: "回復",
    result_kicker: "前線レポート", result_victory: "勝利！", result_defeat: "敗北…", result_draw: "引き分け！", result_victory_message: "ねこ部隊が栄光を守りました！", result_defeat_message: "あきらめないで。部隊を調整して再挑戦！", result_boss_message: "Bossが城を守っています。攻城を成功させるにはBossを倒してください！", result_draw_message: "両軍とも強かった。次こそ決着を！", result_unlimited: "無制限", result_base_hp: "自分の城", result_defeated: "撃破数", result_next: "次のステージ", result_levels: "ステージ選択", result_menu: "メインへ",
    pause_title: "ちょっと休憩", pause_body: "前線を止めました。次の一手を考えましょう。", pause_resume: "戦闘を再開", pause_save_exit: "保存してメインへ", pause_restart: "このステージを再挑戦",
    confirm_title: "よろしいですか？", confirm_body: "現在の進行状況が上書きされます。", confirm_new_body: "新しいゲームを始めると進行状況と戦闘データが消えます。始めますか？", confirm_clear_body: "スターと進行中の戦闘をすべて消去します。設定は残ります。", confirm_no: "やめる", confirm_yes: "確定", toast_saved: "進行状況を保存しました", toast_cleared: "セーブを消去しました", toast_audio: "画面をクリックすると音楽が始まります", toast_income_upgraded: "エネルギーをLV{level}に強化！上限は{max}です。",
    loading: "前線を準備中…", level_locked_hint: "前のステージをクリアして解放"
  };
})(window);
