(function (global) {
  global.LANG_ZH = {
    game_eyebrow: "可愛戰線作戰室", game_title: "Tug of War TD", game_subtitle: "萌貓與魔物的戰線對決", game_tagline: "召喚、推線、守住城堡！",
    menu_start: "開始遊戲", menu_continue: "繼續遊戲", menu_howto: "遊戲說明", menu_settings: "設定", menu_no_save: "尚無可繼續的戰局", menu_continue_ready: "已有進度，點此接續", menu_offline: "離線即可遊玩", menu_autosave: "自動保存進度", footer_local: "純前端・雙擊即玩",
    level_eyebrow: "戰線地圖", level_select: "選擇關卡", level_lead: "所有關卡都可自由挑戰，選一條你想突破的戰線。", level_locked: "尚未解鎖", level_unlocked: "已解鎖", level_stars: "星", level_best: "最佳剩餘", level_play: "出擊", level_back: "返回", difficulty_1: "新兵訓練", difficulty_2: "小隊演習", difficulty_3: "前線交鋒", difficulty_4: "王牌試煉", difficulty_5: "城堡決戰", difficulty_6: "Boss 強化戰",
    level_1_name: "草莓雲朵坡", level_1_desc: "暖身戰！熟悉能量與基本兵的節奏。", level_2_name: "蔚藍潮汐谷", level_2_desc: "遠程敵人出現，學會用坦克掩護後排。", level_3_name: "翡翠森林線", level_3_desc: "屬性開始交錯，找出最適合的反擊組合。", level_4_name: "琥珀夕照關", level_4_desc: "高壓戰線，爆發兵與治療兵都很重要。", level_5_name: "月光王座", level_5_desc: "最終決戰！只有靈活的指揮能守住城堡。", level_6_name: "王冠無限防線", level_6_desc: "強化挑戰：敵方每少 10% 血量就召喚一隻大 Boss。",
    how_eyebrow: "新手指揮官手冊", how_title: "遊戲說明", how_tab_basic: "基本操作", how_tab_resource: "資源系統", how_tab_units: "單位圖鑑", how_tab_matchup: "屬性剋制", how_tab_victory: "勝利條件", how_prev: "上一頁", how_next: "下一頁",
    how_basics_heading: "拉起你的勝利繩！", how_basics_intro: "在同一條戰線上派出小隊，讓對手的城堡先倒下。", how_basic_1_title: "累積能量", how_basic_1_desc: "能量會隨時間回復，觀察左側能量條再決定召喚節奏。", how_basic_2_title: "選擇單位", how_basic_2_desc: "點擊底部卡片召喚單位。不同兵種各有成本、冷卻與定位。", how_basic_3_title: "推進戰線", how_basic_3_desc: "單位會自動前進並戰鬥，你的任務是做出更好的派兵決策。", how_basic_4_title: "守護基地", how_basic_4_desc: "敵人突破防線時會攻擊你的城堡，必要時留能量反守為攻。",
    how_resource_heading: "能量就是節奏", how_resource_intro: "不要一次花光，讓高低成本單位互相掩護，戰線才會穩。", how_resource_1_title: "上限 100+", how_resource_1_desc: "每個關卡有不同能量上限與回復速度，難度越高節奏越快。", how_resource_2_title: "量力召喚", how_resource_2_desc: "卡片上的數字是召喚成本，灰色卡片代表目前能量不足。", how_resource_3_title: "留意冷卻", how_resource_3_desc: "強力單位不能連續召喚，搭配基礎兵填補空檔最有效率。", how_resource_4_title: "推線回報", how_resource_4_desc: "擊破敵人後把握空檔累積能量，準備下一波攻勢。",
    how_units_heading: "認識你的隊伍", how_units_intro: "十三種常駐與特殊兵種各司其職，先用便宜兵種穩住戰線，再找機會爆發。", how_matchup_heading: "屬性相剋表", how_matchup_intro: "看清敵人的色彩標記，剋制屬性可造成雙倍傷害。", how_victory_heading: "三種方式拿下勝利", how_victory_intro: "聰明地推進戰線，星星會記住你的表現。",
    how_victory_1_title: "摧毀城堡", how_victory_1_desc: "敵方基地血量歸零且 Boss 全數擊敗才算勝利；自己的基地歸零則戰敗。", how_victory_2_title: "時間結束", how_victory_2_desc: "倒數結束時若仍有 Boss 存活，無法判定推城勝利；否則比較雙方基地百分比。", how_victory_3_title: "收集星級", how_victory_3_desc: "剩餘時間與基地血量越高，結算星級越漂亮，最多三顆星。", how_victory_4_title: "所有關卡開放", how_victory_4_desc: "每一關都可直接挑戰，通關成績與戰鬥進度會自動保存。",
    matchup_attacker: "攻擊方", matchup_effective: "剋制", matchup_note: "效果", matchup_double: "傷害 ×2", matchup_neutral: "穩定但沒有額外加成", attribute_red: "紅色", attribute_angel: "天使", attribute_demon: "惡魔", attribute_metal: "金屬", attribute_normal: "一般",
    settings_eyebrow: "打造你的作戰室", settings_title: "設定", settings_audio: "音訊設定", settings_audio_hint: "明亮飽滿的音色，並以限幅器保護耳朵。", settings_bgm_volume: "音樂音量", settings_sfx_volume: "音效音量", settings_sound_on: "音效開啟", settings_sound_off: "音效靜音", settings_mute_hint: "一鍵暫停所有聲音", settings_theme: "主題配色", settings_theme_hint: "選一個今天最想守護的天空。", settings_language: "語言設定", settings_language_hint: "即時切換，偏好會自動保存。", settings_data: "資料管理", settings_data_hint: "清除已保存的關卡與進行中的戰局。", settings_clear_save: "清除存檔", theme_cute: "可愛粉色", theme_ocean: "海洋藍", theme_forest: "森林綠", theme_sunset: "夕陽橘", theme_night: "夜間模式", lang_zh: "中文", lang_en: "English", lang_ja: "日本語",
    battle_you: "我方城堡", battle_enemy: "敵方城堡", battle_energy: "能量", battle_energy_tip: "穩住節奏！", battle_lane_you: "貓咪防線", battle_lane_enemy: "魔物防線", battle_summon: "召喚小隊", battle_summon_hint: "點擊卡片，把夥伴送上戰線", battle_cost: "費用", battle_ready: "可出擊", battle_cooldown: "冷卻", battle_insufficient: "能量不足", battle_spawned: "出擊！", battle_wave: "敵方來襲！", battle_paused: "戰線暫停", battle_income_upgrade: "能量升級", battle_upgrade_cost: "費用", battle_upgrade_max: "已達最高 LV5", battle_boss: "大 Boss", battle_boss_warning: "Boss 來襲！目前 {count} 隻", unit_attribute: "屬性", unit_attack: "攻擊", unit_hp: "生命", unit_speed: "速度", unit_range: "射程",
    unit_basic_name: "基礎兵", unit_basic_desc: "便宜可靠的前排夥伴，適合大量派出。", unit_ranger_name: "遠程兵", unit_ranger_desc: "在後方安全輸出，血量較低需要保護。", unit_tank_name: "重裝兵", unit_tank_desc: "超厚血量的盾牌，慢慢把戰線往前推。", unit_striker_name: "爆發兵", unit_striker_desc: "一擊很痛的突擊手，冷卻與成本都較高。", unit_healer_name: "治療兵", unit_healer_desc: "為受傷夥伴恢復生命，讓前線持續作戰。", unit_scout_name: "偵查兵", unit_scout_desc: "高速穿梭的便宜先鋒，搶在敵人前面推線。", unit_guard_name: "守衛兵", unit_guard_desc: "穩定的中型盾牌，補上前線的防守缺口。", unit_catapult_name: "投石兵", unit_catapult_desc: "遠距離重砲，攻擊速度慢但每一發都很有份量。", unit_berserker_name: "狂戰士", unit_berserker_desc: "生命越低越狂暴，危急時能打出驚人傷害。", unit_frost_name: "冰霜法師", unit_frost_desc: "以冰霜命中敵人，讓敵人的移動速度大幅下降。", unit_thunder_name: "雷電法師", unit_thunder_desc: "雷擊會跳向附近敵人，清理成群的敵軍。", unit_guardian_name: "護盾守護者", unit_guardian_desc: "週期性為附近夥伴張開護盾，吸收即將到來的傷害。", unit_summoner_name: "召喚師", unit_summoner_desc: "每隔一段時間免費召喚一名基礎兵，持續擴大隊伍。", unit_boss_name: "王冠大 Boss", unit_boss_desc: "守護城堡的巨大敵人，必須擊敗才能繼續攻城。", unit_role_tank: "前排", unit_role_ranged: "遠程", unit_role_heavy: "坦克", unit_role_burst: "爆發", unit_role_support: "支援", unit_role_speed: "高速", unit_role_guard: "守衛", unit_role_siege: "攻城", unit_role_special: "特殊", unit_role_boss: "Boss", unit_ability_rage: "狂暴", unit_ability_frost: "冰霜減速", unit_ability_chain: "鏈雷", unit_ability_barrier: "護盾", unit_ability_summon: "免費召喚", attack_melee: "近戰", attack_ranged: "遠程", attack_support: "治療",
    result_kicker: "戰線報告", result_victory: "勝利！", result_defeat: "戰敗…", result_draw: "平局！", result_victory_message: "你的貓咪小隊守住了榮耀！", result_defeat_message: "別灰心，調整隊伍再來一次！", result_boss_message: "Boss 還在守城，必須先擊敗它才能攻下城堡！", result_draw_message: "雙方都很頑強，下一次分出高下吧！", result_time: "剩餘時間", result_base_hp: "我方城堡", result_defeated: "擊破敵人", result_next: "下一關", result_levels: "返回選關", result_menu: "返回主畫面",
    pause_title: "暫停一下", pause_body: "戰線暫時靜止，想好下一步再出發。", pause_resume: "繼續戰鬥", pause_save_exit: "保存並返回主畫面", pause_restart: "重新挑戰本關",
    confirm_title: "確定嗎？", confirm_body: "這個動作會覆蓋目前的進度。", confirm_new_body: "開始新遊戲會清除目前的關卡進度與戰局，確定要重新出發嗎？", confirm_clear_body: "所有關卡星級與進行中的戰局都會被清除，設定不受影響。", confirm_no: "先不要", confirm_yes: "確定", toast_saved: "進度已保存", toast_cleared: "存檔已清除", toast_audio: "點擊畫面後即可播放音樂", toast_income_upgraded: "能量升級至 LV{level}！上限提高到 {max}！",
    loading: "正在準備戰線…", level_locked_hint: "先完成前一關解鎖"
  };
})(window);
