(function (global) {
  global.LANG_EN = {
    game_eyebrow: "Cute Frontline Command", game_title: "Tug of War TD", game_subtitle: "Cats versus monsters on one mighty lane", game_tagline: "Summon, push, protect your castle!",
    menu_start: "New Game", menu_continue: "Continue", menu_howto: "How to Play", menu_settings: "Settings", menu_no_save: "No saved battle yet", menu_continue_ready: "Continue your progress", menu_offline: "Works offline", menu_autosave: "Auto-saves progress", footer_local: "Pure frontend · Double-click to play",
    level_eyebrow: "Frontline Map", level_select: "Choose a Level", level_lead: "Push forward node by node and unlock new enemies and challenges.", level_locked: "Locked", level_unlocked: "Unlocked", level_stars: "Stars", level_best: "Best left", level_play: "Deploy", level_back: "Back", difficulty_1: "Rookie Drill", difficulty_2: "Squad Exercise", difficulty_3: "Frontline Clash", difficulty_4: "Ace Trial", difficulty_5: "Castle Showdown",
    level_1_name: "Strawberry Cloud Hill", level_1_desc: "A warm-up battle to learn energy and basic units.", level_2_name: "Azure Tide Valley", level_2_desc: "Ranged foes arrive. Let tanks cover your back line.", level_3_name: "Emerald Forest Line", level_3_desc: "Attributes mix together. Find the perfect counter push.", level_4_name: "Amber Sunset Gate", level_4_desc: "A high-pressure line where burst and healing both matter.", level_5_name: "Moonlit Throne", level_5_desc: "The final showdown. Only a flexible commander can hold the castle.",
    how_eyebrow: "Field Manual for New Commanders", how_title: "How to Play", how_tab_basic: "Basics", how_tab_resource: "Resources", how_tab_units: "Unit Guide", how_tab_matchup: "Matchups", how_tab_victory: "Victory", how_prev: "Previous", how_next: "Next",
    how_basics_heading: "Pull your way to victory!", how_basics_intro: "Deploy squads on one shared lane and make the enemy castle fall first.", how_basic_1_title: "Build energy", how_basic_1_desc: "Energy returns over time. Watch the left energy bar before choosing your tempo.", how_basic_2_title: "Pick a unit", how_basic_2_desc: "Tap a card at the bottom. Each unit has a cost, cooldown, and role.", how_basic_3_title: "Push the lane", how_basic_3_desc: "Units advance and fight automatically; your job is making smart deployment calls.", how_basic_4_title: "Guard the base", how_basic_4_desc: "Breakthrough enemies attack your castle. Save energy to turn defense into offense.",
    how_resource_heading: "Energy sets the tempo", how_resource_intro: "Do not spend it all at once. Mix cheap and expensive units to stabilize the line.", how_resource_1_title: "100+ cap", how_resource_1_desc: "Each level has its own energy cap and recovery rate. Harder levels move faster.", how_resource_2_title: "Spend wisely", how_resource_2_desc: "The number on a card is its summon cost. A grey card means you are short on energy.", how_resource_3_title: "Watch cooldowns", how_resource_3_desc: "Powerful units cannot chain instantly. Use basic units to fill the gaps.", how_resource_4_title: "Reward the push", how_resource_4_desc: "After defeating foes, use the breathing room to build the next attack.",
    how_units_heading: "Meet your squad", how_units_intro: "Five core units have distinct jobs. Stabilize first, then look for a burst window.", how_matchup_heading: "Attribute matchups", how_matchup_intro: "Read the enemy color tags. A counter attribute deals double damage.", how_victory_heading: "Three ways to win", how_victory_intro: "Push smartly and the stars will remember your performance.",
    how_victory_1_title: "Destroy the castle", how_victory_1_desc: "Enemy base HP reaching zero wins instantly; losing your own means defeat.", how_victory_2_title: "Beat the clock", how_victory_2_desc: "When time ends, the higher base-health percentage wins.", how_victory_3_title: "Collect stars", how_victory_3_desc: "More remaining time and castle HP means a brighter result, up to three stars.", how_victory_4_title: "Unlock levels", how_victory_4_desc: "A clear auto-saves and unlocks the next node. Continue any time.",
    matchup_attacker: "Attacker", matchup_effective: "Counters", matchup_note: "Effect", matchup_double: "Damage ×2", matchup_neutral: "Steady, no bonus", attribute_red: "Red", attribute_angel: "Angel", attribute_demon: "Demon", attribute_metal: "Metal", attribute_normal: "Normal",
    settings_eyebrow: "Build your command room", settings_title: "Settings", settings_audio: "Audio", settings_audio_hint: "Bright, full tones with a limiter for safer listening.", settings_bgm_volume: "Music volume", settings_sfx_volume: "SFX volume", settings_sound_on: "Sound on", settings_sound_off: "Sound muted", settings_mute_hint: "Pause all audio with one tap", settings_theme: "Color theme", settings_theme_hint: "Choose the sky you want to protect today.", settings_language: "Language", settings_language_hint: "Switch instantly; your preference is saved.", settings_data: "Data management", settings_data_hint: "Clear saved levels and active battles.", settings_clear_save: "Clear save", theme_cute: "Cute Pink", theme_ocean: "Ocean Blue", theme_forest: "Forest Green", theme_sunset: "Sunset Orange", theme_night: "Night Mode", lang_zh: "中文", lang_en: "English", lang_ja: "日本語",
    battle_you: "Your castle", battle_enemy: "Enemy castle", battle_energy: "Energy", battle_energy_tip: "Hold the tempo!", battle_lane_you: "Cat frontline", battle_lane_enemy: "Monster frontline", battle_summon: "Summon squad", battle_summon_hint: "Tap a card to send a friend to the frontline", battle_cost: "Cost", battle_ready: "Ready", battle_cooldown: "Cooldown", battle_insufficient: "Not enough energy", battle_spawned: "Deploy!", battle_wave: "Enemy incoming!", battle_paused: "Frontline paused", unit_attribute: "Attribute", unit_attack: "Attack", unit_hp: "HP", unit_speed: "Speed", unit_range: "Range",
    unit_basic_name: "Basic", unit_basic_desc: "A cheap, reliable frontline friend for numbers.", unit_ranger_name: "Ranger", unit_ranger_desc: "Safe backline damage, but fragile and needs cover.", unit_tank_name: "Heavy", unit_tank_desc: "A thick shield that slowly pushes the lane forward.", unit_striker_name: "Striker", unit_striker_desc: "A hard-hitting diver with a high cost and cooldown.", unit_healer_name: "Healer", unit_healer_desc: "Restores allies so the frontline can keep fighting.", unit_role_tank: "Frontline", unit_role_ranged: "Ranged", unit_role_heavy: "Tank", unit_role_burst: "Burst", unit_role_support: "Support", attack_melee: "Melee", attack_ranged: "Ranged", attack_support: "Heal",
    result_kicker: "Frontline Report", result_victory: "Victory!", result_defeat: "Defeat…", result_draw: "Draw!", result_victory_message: "Your cat squad defended its glory!", result_defeat_message: "Do not give up. Tune the squad and try again!", result_draw_message: "Both sides held strong. Settle it next time!", result_time: "Time left", result_base_hp: "Your castle", result_defeated: "Defeated", result_next: "Next level", result_levels: "Level select", result_menu: "Main menu",
    pause_title: "Take a pause", pause_body: "The frontline is frozen. Plan your next move.", pause_resume: "Resume battle", pause_save_exit: "Save & main menu", pause_restart: "Restart this level",
    confirm_title: "Are you sure?", confirm_body: "This action will overwrite your current progress.", confirm_new_body: "Starting a new game clears current progress and battle data. Leave for a fresh start?", confirm_clear_body: "All stars and active battles will be cleared. Your settings stay safe.", confirm_no: "Not yet", confirm_yes: "Confirm", toast_saved: "Progress saved", toast_cleared: "Save cleared", toast_audio: "Click the screen to start the music",
    loading: "Preparing the frontline…", level_locked_hint: "Clear the previous level to unlock"
  };
})(window);
