(function (PSG) {
  'use strict';
  var d = PSG.utils.dom;
  function render(root, data) {
    var save = PSG.core.gameState.get(); if (!save || !data.opponent) return PSG.core.scenes.go('ranking');
    var state = PSG.battle.engine.create(save, data.opponent, data.consumableId);
    var started = PSG.battle.engine.start(state); if (!started.ok) { PSG.ui.common.toast(PSG.ui.common.actionReason(save, 'battle'), 'error'); return PSG.core.scenes.go('ranking'); }
    var stopped = false, timer = 0;
    function logHtml(log) {
      var t = PSG.i18n.t, attacker = log.attacker === 'player' ? state.player : state.enemy, defender = log.defender === 'player' ? state.player : state.enemy;
      if (log.dodged) return '💨 ' + t('battle.log.dodge', { defender: d.escape(defender.name), attack: t(log.attackKey) });
      return (log.critical ? '💥 ' + t('battle.log.crit') + ' ' : '') + t('battle.log.hit', { attacker: d.escape(attacker.name), attack: t(log.attackKey), damage: log.hpDamage }) + (log.shieldAbsorbed ? ' ' + t('battle.log.shield', { value: log.shieldAbsorbed }) : '');
    }
    function paint() {
      var t = PSG.i18n.t, playerSpecies = PSG.data.species[state.player.speciesId], enemySpecies = PSG.data.species[state.enemy.speciesId];
      root.innerHTML = '<section class="scene battle-layout"><header class="scene-header"><div class="scene-header__title"><img src="assets/images/ui/logo-mark.svg" alt=""><div><span class="eyebrow">' + t('battle.title') + '</span><h2 id="round-label">' + t('battle.round', { round: Math.max(1, state.round + (state.round ? 0 : 1)) }) + '</h2></div></div><label class="tag"><input id="fast-battle" type="checkbox" ' + (PSG.core.settings.motion !== 'standard' ? 'checked' : '') + '> ' + t('battle.fast') + '</label></header><div class="battle-arena"><article class="fighter"><h3>' + d.escape(state.player.name) + ' · LV ' + state.player.level + '</h3>' + d.bar('HP', state.player.hp, state.player.maxHp, '♥', state.player.hp / state.player.maxHp < .3 ? 'danger' : 'primary') + d.bar('ENERGY', state.player.energy, 100, '⚡', 'energy') + (state.player.shield ? '<span class="tag">🛡 ' + state.player.shield + '</span>' : '') + '<img class="fighter__portrait" id="player-fighter" src="' + playerSpecies.image + '" alt="' + d.escape(state.player.name) + '"></article><div class="versus"><span>' + t('battle.round', { round: Math.max(1,state.round) }) + '</span><strong>VS</strong><span>20 MAX</span></div><article class="fighter enemy"><h3>' + d.escape(state.enemy.name) + ' · LV ' + state.enemy.level + '</h3>' + d.bar('HP', state.enemy.hp, state.enemy.maxHp, '♥', state.enemy.hp / state.enemy.maxHp < .3 ? 'danger' : 'primary') + d.bar('ENERGY', state.enemy.energy, 100, '⚡', 'energy') + (state.enemy.shield ? '<span class="tag">🛡 ' + state.enemy.shield + '</span>' : '') + '<img class="fighter__portrait" id="enemy-fighter" src="' + enemySpecies.image + '" alt="' + d.escape(state.enemy.name) + '"></article></div><div class="battle-bottom"><div class="card battle-log" aria-live="polite"><ol reversed>' + state.logs.slice().reverse().map(function (log) { return '<li>' + logHtml(log) + '</li>'; }).join('') + '</ol></div><div class="battle-commands"><button class="button" type="button" data-command="normal">⚔ <span>' + t('battle.normal') + '</span></button><button class="button button--secondary" type="button" data-command="special" ' + (state.player.energy < 100 ? 'disabled' : '') + '>✦ <span>' + t('battle.special') + '<small style="display:block">' + t('battle.energyNeed', { energy: state.player.energy }) + '</small></span></button></div></div></section>';
      d.all('[data-command]', root).forEach(function (button) { button.addEventListener('click', function () { if (stopped || state.ended) return; stopped = true; d.all('[data-command]', root).forEach(function (item) { item.disabled = true; }); var outcome = PSG.battle.engine.round(state, button.dataset.command); animate(outcome.events, function () { stopped = false; if (state.ended) finish(); else paint(); }); }); });
    }
    function animate(events, done) {
      var fast = d.one('#fast-battle', root) && d.one('#fast-battle', root).checked, delay = fast ? 90 : 380, index = 0;
      function next() { if (index >= events.length) return done(); var event = events[index++], attacker = d.one(event.attacker === 'player' ? '#player-fighter' : '#enemy-fighter', root), defender = d.one(event.defender === 'player' ? '#player-fighter' : '#enemy-fighter', root); if (attacker) attacker.animate([{transform:'translateX(0)'},{transform:'translateX(' + (event.attacker === 'player' ? '7%' : '-7%') + ') scale(1.03)'},{transform:'translateX(0)'}],{duration:delay,easing:'ease-out'}); if (defender && event.dodged) defender.animate([{transform:'translateX(0)'},{transform:'translateX(' + (event.defender === 'player' ? '-8%' : '8%') + ')'},{transform:'translateX(0)'}],{duration:delay}); else if (defender) defender.animate([{filter:'brightness(1)'},{filter:'brightness(1.7) saturate(.4)'},{filter:'brightness(1)'}],{duration:delay}); PSG.audio.manager.sfx(event.dodged ? 'dodge' : event.critical ? 'critical' : event.action === 'special' ? 'special' : 'attack'); timer = window.setTimeout(next, delay); } next();
    }
    function finish() {
      var result = PSG.battle.engine.settle(state), t = PSG.i18n.t;
      PSG.audio.manager.sfx(result.won ? 'victory' : 'defeat');
      if (result.champion) PSG.audio.manager.play('champion');
      PSG.ui.common.modal({ required: true, eyebrow: state.reason === 'turnLimit' ? t('battle.turnLimit') : t('battle.title'), title: result.won ? t('battle.victory') : t('battle.defeat'), body: '<div class="event-art" style="min-height:180px;font-size:5rem">' + (result.won ? '🏆✨' : '🌙🤝') + '</div><h3 style="margin-top:1rem">' + t('battle.reward', { xp: result.xp.gained, coins: result.coins }) + '</h3>' + (result.rank.changed ? '<p>' + t('battle.rankUp', { rank: result.rank.after }) + '</p>' : '') + (result.firstMilestone ? '<blockquote class="card card--soft" style="margin-top:1rem">' + t('ranking.milestoneDefeat') + '</blockquote>' : '') + (result.champion ? '<div class="card card--soft" style="margin-top:1rem"><h3>' + t('champion.title') + '</h3><p>' + t('champion.body', { playerName: d.escape(save.player.name), petName: d.escape(save.pet.name) }) + '</p></div>' : ''), actions: PSG.ui.common.button(t('battle.return'), 'battle-finish'), onOpen: function (dialog) { d.one('[data-action="battle-finish"]', dialog).addEventListener('click', function () { PSG.ui.common.closeModal(); if (save.day.actionPoints === 0) PSG.ui.common.completeDay(save); PSG.core.scenes.go(result.champion ? 'home' : 'ranking'); }); } });
    }
    paint();
    return function () { stopped = true; clearTimeout(timer); };
  }
  PSG.ui.battle = { render: render };
})(window.PSG);
