(function (PSG) {
  'use strict';
  var d = PSG.utils.dom;
  function showPending(save) {
    var id = PSG.pet.affection.nextPending(save); if (!id) return false;
    var threshold = Number(id.split('_').pop()), t = PSG.i18n.t;
    PSG.ui.common.modal({ required: true, eyebrow: t('affection.title'), title: t('affection.' + threshold), body: '<div class="event-art"><span>' + PSG.data.species[save.pet.speciesId].icon + '💞</span></div><p style="margin-top:1rem">' + t('affection.story.' + save.pet.speciesId, { petName: d.escape(save.pet.name) }) + '</p><p class="muted">' + t('affection.reward') + '</p>', actions: PSG.ui.common.button(t('common.next'), 'affection-close'), onOpen: function (dialog) { d.one('[data-action="affection-close"]', dialog).addEventListener('click', function () { PSG.pet.affection.markViewed(save, id); PSG.storage.save.write(save); PSG.ui.common.closeModal(); window.setTimeout(function () { showPending(save); }, 80); }); } });
    return true;
  }
  function actionButton(save, action, icon, label, scene) {
    var reason = PSG.ui.common.actionReason(save, action); return '<button class="button ' + (action === 'rest' ? 'button--secondary' : '') + '" type="button" data-home-action="' + action + '" ' + (scene ? 'data-target="' + scene + '"' : '') + ' ' + (reason ? 'disabled title="' + d.escape(reason) + '"' : '') + '><span>' + icon + '</span><span>' + label + '</span></button>';
  }
  function render(root) {
    var save = PSG.core.gameState.get(); if (!save) return PSG.core.scenes.go('menu');
    // A reload can occur between an activity settlement and its result modal closing.
    // Completing the pending zero-AP day here keeps the daily loop impossible to strand.
    if (save.day.actionPoints === 0) PSG.pet.daily.nextDay(save);
    var t = PSG.i18n.t, species = PSG.data.species[save.pet.speciesId], stats = PSG.pet.stats.effective(save), bp = PSG.pet.stats.battlePower(save), rank = PSG.ranking.matchmaking.playerRank(save), state = PSG.pet.model.statusLabel(save);
    var xpMax = save.pet.level >= 100 ? 1 : PSG.pet.progression.xpToNext(save.pet.level), xpValue = save.pet.level >= 100 ? 1 : save.pet.xp;
    root.innerHTML = '<section class="scene">' + PSG.ui.common.topbar(save) + '<div class="home-layout"><aside class="card pet-summary"><div class="identity-block"><span class="identity-block__icon">' + species.icon + '</span><div style="min-width:0"><span class="eyebrow">' + t(species.nameKey) + '</span><h2 title="' + d.escape(save.pet.name) + '" style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">' + d.escape(save.pet.name) + '</h2></div></div><div class="card card--soft"><div class="card__header"><strong>' + t('common.level', { level: save.pet.level }) + '</strong><span>' + t('common.bp', { bp: PSG.utils.formatter.number(bp) }) + '</span></div>' + d.bar(t('stat.xp'), xpValue, xpMax, '✦', 'primary') + '</div><div class="stat-grid">' + PSG.constants.STAT_KEYS.map(function (key) { return '<span class="stat-chip"><span>' + t('stat.' + key) + '</span><strong>' + stats[key] + '</strong></span>'; }).join('') + '</div></aside><div class="pet-stage" data-state="' + (state === 'high' ? 'happy' : state === 'low' ? 'tired' : 'idle') + '"><img class="pet-stage__portrait" src="' + species.image + '" alt="' + t(species.nameKey) + ' ' + d.escape(save.pet.name) + '"><div class="pet-stage__bubble">' + t('home.talk.' + state) + '</div></div><aside class="card status-panel"><div class="panel-title"><div><span class="eyebrow">' + t('home.greeting', { playerName: d.escape(save.player.name), petName: d.escape(save.pet.name) }) + '</span><h3>' + t('common.rank', { rank: rank }) + '</h3></div></div>' + d.bar(t('stat.energy'), save.pet.energy, 100, '⚡', 'energy') + d.bar(t('stat.mood'), save.pet.mood, 100, '☀', 'mood') + d.bar(t('stat.affection'), save.pet.affection, 100, '♥', 'bond') + d.bar(t('stat.ap'), save.day.actionPoints, 5, '◆', 'primary') + '</aside><section class="card action-panel"><div class="panel-title"><h3>' + t('home.day', { day: save.day.number }) + '</h3><span class="muted">' + t('home.restHint') + '</span></div><div class="action-grid">' + actionButton(save,'training','🎯',t('home.training'),'training') + actionButton(save,'play','🎾',t('home.play')) + actionButton(save,'outing','🧭',t('home.outing'),'outing') + actionButton(save,'battle','🏆',t('home.ranking'),'ranking') + '<button class="button" type="button" data-target="shop">🛍 ' + t('home.shop') + '</button><button class="button" type="button" data-target="shop" data-shop-tab="inventory">🛡 ' + t('home.equipment') + '</button>' + actionButton(save,'rest','🌙',t('home.rest')) + '</div></section></div></section>';
    d.all('[data-target]', root).forEach(function (button) { button.addEventListener('click', function () { PSG.audio.manager.sfx('click'); PSG.core.scenes.go(button.dataset.target, { tab: button.dataset.shopTab }); }); });
    var play = d.one('[data-home-action="play"]', root); if (play) play.addEventListener('click', function () { var result = PSG.pet.play.perform(save); if (!result.ok) return; PSG.audio.manager.sfx('bond'); PSG.ui.common.modal({ title: t('home.play'), body: '<div class="event-art"><span>' + species.icon + '✨</span></div><h3 style="margin-top:1rem">' + t('play.' + result.id) + '</h3><p>' + t('play.result', { petName: d.escape(save.pet.name), xp: result.xp.gained }) + '</p>', actions: PSG.ui.common.button(t('common.confirm'), 'play-close'), onOpen: function (dialog) { d.one('[data-action="play-close"]', dialog).addEventListener('click', function () { PSG.ui.common.closeModal(); if (save.day.actionPoints === 0) PSG.ui.common.completeDay(save); render(root); showPending(save); }); } }); });
    var rest = d.one('[data-home-action="rest"]', root); if (rest) rest.addEventListener('click', function () { PSG.ui.common.completeDay(save); PSG.audio.manager.sfx('confirm'); render(root); showPending(save); });
    window.setTimeout(function () { showPending(save); }, 120);
  }
  PSG.ui.home = { render: render, showPending: showPending };
})(window.PSG);
