(function (PSG) {
  'use strict';
  var data = { step: 1, playerName: '', speciesId: null, petName: '' };
  var d = PSG.utils.dom;
  function render(root) {
    var t = PSG.i18n.t;
    var body = '';
    if (data.step === 1) body = '<div class="form-stack"><span class="eyebrow">01 / 03</span><h1>' + t('onboard.playerTitle') + '</h1><label for="player-name"><strong>' + t('onboard.playerLabel') + '</strong></label><input class="text-input" id="player-name" maxlength="24" autocomplete="name" value="' + d.escape(data.playerName) + '"><p class="muted" id="name-hint">1–12 Unicode</p><div class="scene-actions"><button class="button button--ghost" type="button" data-scene="menu">' + t('nav.back') + '</button><button class="button" type="button" data-action="player-next">' + t('common.next') + ' →</button></div></div>';
    if (data.step === 2) body = '<span class="eyebrow">02 / 03</span><h1>' + t('onboard.chooseTitle') + '</h1><p class="muted">' + t('onboard.chooseHint') + '</p><div class="species-grid">' + Object.keys(PSG.data.species).map(function (id) { var species = PSG.data.species[id], stats = species.base; return '<button type="button" class="card species-card ' + (data.speciesId === id ? 'is-selected' : '') + '" data-species="' + id + '"><img src="' + species.image + '" alt="' + t(species.nameKey) + '"><span class="species-card__body"><span class="eyebrow">' + t(species.nameKey + '.role') + '</span><strong>' + species.icon + ' ' + t(species.nameKey) + '</strong><span class="species-mini-stats"><span>HP ' + stats.hp + '</span><span>ATK ' + stats.attack + '</span><span>SPE ' + stats.speed + '</span></span></span></button>'; }).join('') + '</div><div class="scene-actions"><button class="button button--ghost" type="button" data-action="step-back">' + t('nav.back') + '</button><button class="button" type="button" data-action="species-next" ' + (data.speciesId ? '' : 'disabled') + '>' + t('common.next') + ' →</button></div>';
    if (data.step === 3) { var species = PSG.data.species[data.speciesId]; body = '<div class="event-scene"><div class="event-art" style="padding:0;overflow:hidden"><img src="' + species.image + '" alt="' + t(species.nameKey) + '" style="width:100%;height:100%;object-fit:cover"></div><div class="form-stack"><span class="eyebrow">03 / 03</span><h1>' + t('onboard.petTitle') + '</h1><label for="pet-name"><strong>' + t('onboard.petLabel') + '</strong></label><input class="text-input" id="pet-name" maxlength="24" value="' + d.escape(data.petName) + '"><p class="muted">' + t(species.nameKey) + ' · ' + t(species.nameKey + '.role') + '</p><div class="scene-actions"><button class="button button--ghost" type="button" data-action="step-back">' + t('nav.back') + '</button><button class="button" type="button" data-action="begin">' + t('onboard.begin') + ' ✦</button></div></div></div>'; }
    root.innerHTML = '<section class="scene onboarding-wrap"><div class="onboarding-card">' + body + '</div></section>';
    var next = d.one('[data-action="player-next"]', root); if (next) next.addEventListener('click', function () { var valid = PSG.utils.validator.name(d.one('#player-name', root).value); if (!valid.valid) return PSG.ui.common.toast(t('onboard.nameError'), 'error'); data.playerName = valid.value; data.step = 2; render(root); });
    d.all('[data-species]', root).forEach(function (button) { button.addEventListener('click', function () { data.speciesId = button.dataset.species; render(root); }); });
    var speciesNext = d.one('[data-action="species-next"]', root); if (speciesNext) speciesNext.addEventListener('click', function () { data.step = 3; render(root); });
    var back = d.one('[data-action="step-back"]', root); if (back) back.addEventListener('click', function () { data.step -= 1; render(root); });
    var begin = d.one('[data-action="begin"]', root); if (begin) begin.addEventListener('click', function () { var valid = PSG.utils.validator.name(d.one('#pet-name', root).value); if (!valid.valid) return PSG.ui.common.toast(t('onboard.nameError'), 'error'); data.petName = valid.value; var save = PSG.core.gameState.create(data.playerName, data.petName, data.speciesId); PSG.core.gameState.set(save); PSG.storage.save.write(save); PSG.audio.manager.sfx('confirm'); showTutorial(save, 1); });
  }
  function showTutorial(save, step) {
    var t = PSG.i18n.t;
    PSG.ui.common.modal({ required: true, eyebrow: step + ' / 5', title: t('tutorial.' + step + '.title'), body: '<div class="event-art" style="min-height:150px;font-size:4rem">' + ['💗','⚡','🎯','🛡️','🏆'][step - 1] + '</div><p style="margin-top:1rem">' + t('tutorial.' + step + '.body') + '</p><div class="tutorial-dots" style="margin-top:1rem">' + [1,2,3,4,5].map(function (n) { return '<span class="tutorial-dot ' + (n === step ? 'is-active' : '') + '"></span>'; }).join('') + '</div>', actions: PSG.ui.common.button(t('common.skip'), 'tutorial-skip', 'ghost') + PSG.ui.common.button(step === 5 ? t('common.confirm') : t('common.next'), 'tutorial-next'), onOpen: function (dialog) {
      d.one('[data-action="tutorial-skip"]', dialog).addEventListener('click', finish);
      d.one('[data-action="tutorial-next"]', dialog).addEventListener('click', function () { if (step < 5) showTutorial(save, step + 1); else finish(); });
      function finish() { save.progression.tutorialCompleted = true; PSG.storage.save.write(save); PSG.ui.common.closeModal(); data = { step: 1, playerName: '', speciesId: null, petName: '' }; PSG.core.scenes.go('home'); }
    } });
  }
  PSG.ui.onboarding = { render: render, tutorial: showTutorial };
})(window.PSG);
