(function(BB){'use strict';var SETTINGS_KEY='bb_shoot_settings',settings=loadSettings(),i18n=new BB.I18nManager(BB.Langs,settings.language),audio=new BB.AudioManager(),state=new BB.StateManager('MENU'),engine=null;
function q(s){return document.querySelector(s);}function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s));}function loadSettings(){try{return BB.SettingsSchema.validate(JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'));}catch(e){return BB.SettingsSchema.validate({});}}function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch(e){}}
function applySettings(){document.body.dataset.theme=settings.theme;i18n.setLanguage(settings.language);q('#quick-language').value=settings.language;q('#bgm-volume').value=settings.bgmVolume;q('#sfx-volume').value=settings.sfxVolume;q('#bgm-output').value=settings.bgmVolume+'%';q('#sfx-output').value=settings.sfxVolume+'%';q('#trajectory-toggle').checked=settings.trajectory;q('#skin-toggle').checked=settings.cuteSkin;qa('[data-theme-value]').forEach(function(b){b.classList.toggle('selected',b.dataset.themeValue===settings.theme);});qa('[data-lang]').forEach(function(b){b.classList.toggle('active',b.dataset.lang===settings.language);});audio.setVolumes(settings.bgmVolume/100,settings.sfxVolume/100);saveSettings();}
function showScreen(id){qa('.screen').forEach(function(s){s.classList.toggle('active',s.id===id);});}
function openModal(id){q('#modal-root').hidden=false;qa('#modal-root>.modal').forEach(function(m){m.hidden=m.id!==id;});}
function closeModals(){q('#modal-root').hidden=true;qa('#modal-root>.modal').forEach(function(m){m.hidden=true;});}
function startGame(saved){audio.resume();audio.startBgm('game');showScreen('game-screen');closeModals();if(state.state==='MENU'||state.state==='ENDED')state.transition('PLAYING');engine=engine||new BB.GameEngine(q('#game-canvas'),{getSettings:function(){return settings;},onUpdate:updateHud,onSound:function(s){audio.tone(s);},onScore:onScore,onEnd:endGame});engine.start(saved||null);}
function updateHud(data){q('#score-value').textContent=String(data.score).padStart(3,'0');q('#time-value').textContent=Math.ceil(data.time);q('#combo-value').textContent='x'+data.combo;if(Math.ceil(data.time)<=3&&Math.ceil(data.time)>0&&Math.floor(data.time*10)%10===0)audio.tone('count');}
function onScore(points,combo,swish){audio.tone('score',combo);var toast=q('#shot-toast');toast.textContent=(swish?'SWISH! +':'NICE SHOT! +')+points+(combo>1?' 🔥x'+combo:' 💖');toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show');if(settings.vibration&&navigator.vibrate)navigator.vibrate(35);}
function endGame(data){state.transition('ENDED');BB.SaveManager.clear();audio.startBgm('victory');audio.tone('end');q('#result-score').textContent=data.score;q('#save-score-btn').disabled=false;q('#save-score-btn').textContent=i18n.t('result.save');renderLeaderboard();openModal('result-modal');refreshContinue();}
function renderLeaderboard(){var rows=BB.Leaderboard.get(),medals=['🥇','🥈','🥉'];q('#leaderboard').innerHTML='<h3>'+i18n.t('leaderboard.title')+'</h3>'+rows.map(function(r,i){return'<div class="leaderboard-row '+(i<3?'top':'')+'"><b>'+(medals[i]||i+1)+'</b><span>'+r.name+'<small> · '+r.combo+'🔥</small></span><strong>'+r.score+'</strong></div>';}).join('');}
function refreshContinue(){var has=BB.SaveManager.has();q('#continue-btn').disabled=!has;q('#continue-hint').hidden=has;}
function returnMenu(){if(engine&&engine.running){BB.SaveManager.save(engine.snapshot());engine.stop();}audio.startBgm('menu');if(state.state!=='MENU')state.transition('MENU');showScreen('menu-screen');closeModals();refreshContinue();}
q('#start-btn').addEventListener('click',function(){BB.SaveManager.clear();startGame();});q('#continue-btn').addEventListener('click',function(){startGame(BB.SaveManager.load(null));});q('#how-btn').addEventListener('click',function(){openModal('how-modal');});q('#settings-btn').addEventListener('click',function(){openModal('settings-modal');});qa('.modal-close').forEach(function(b){b.addEventListener('click',closeModals);});
q('#pause-btn').addEventListener('click',function(){if(!engine||!engine.running)return;state.transition('PAUSED');engine.pause(true);BB.SaveManager.save(engine.snapshot());openModal('pause-modal');});q('#resume-btn').addEventListener('click',function(){state.transition('PLAYING');closeModals();engine.pause(false);});q('#restart-btn').addEventListener('click',function(){engine.stop();state.transition('MENU');startGame();});qa('.back-menu').forEach(function(b){b.addEventListener('click',returnMenu);});
qa('.tab').forEach(function(tab){tab.addEventListener('click',function(){qa('.tab').forEach(function(t){t.classList.toggle('active',t===tab);});qa('.tab-panel').forEach(function(p){p.classList.toggle('active',p.dataset.panel===tab.dataset.tab);});});});
q('#quick-language').addEventListener('change',function(e){settings.language=e.target.value;applySettings();});qa('[data-lang]').forEach(function(b){b.addEventListener('click',function(){settings.language=b.dataset.lang;applySettings();});});qa('[data-theme-value]').forEach(function(b){b.addEventListener('click',function(){settings.theme=b.dataset.themeValue;applySettings();audio.tone('click');});});
q('#bgm-volume').addEventListener('input',function(e){settings.bgmVolume=Number(e.target.value);applySettings();});q('#sfx-volume').addEventListener('input',function(e){settings.sfxVolume=Number(e.target.value);applySettings();audio.tone('click');});q('#trajectory-toggle').addEventListener('change',function(e){settings.trajectory=e.target.checked;applySettings();});q('#skin-toggle').addEventListener('change',function(e){settings.cuteSkin=e.target.checked;applySettings();});
q('#reset-data-btn').addEventListener('click',function(){if(confirm(i18n.t('settings.reset')+'?')){BB.SaveManager.clear();BB.Leaderboard.clear();refreshContinue();}});q('#save-score-btn').addEventListener('click',function(){var data=engine.snapshot();BB.Leaderboard.add({name:q('#player-name').value,score:data.score,combo:data.bestCombo,date:new Date().toISOString()});renderLeaderboard();this.disabled=true;this.textContent=i18n.t('result.saved');});
q('#enter-arcade-btn').addEventListener('click',function(){audio.resume();audio.tone('start');audio.startBgm('menu');q('#audio-gate').classList.add('is-open');setTimeout(function(){q('#audio-gate').hidden=true;},320);});window.addEventListener('beforeunload',function(){if(engine&&engine.running)BB.SaveManager.save(engine.snapshot());});window.addEventListener('keydown',function(e){if(e.key==='Escape'&&!q('#modal-root').hidden){if(!q('#pause-modal').hidden)return;closeModals();}});
applySettings();i18n.update(document);refreshContinue();window.BBApp={startGame:startGame,returnMenu:returnMenu,getEngine:function(){return engine;},getAudio:function(){return audio;}};})(window.BB=window.BB||{});
