(function (root) {
  root.AutoBattlerLang = root.AutoBattlerLang || {};
  root.AutoBattlerLang.ja = {
    app: { title: "Starry Sprouts", tagline: "夢を植えて、仲間たちに自動で戦ってもらおう！", offline: "オフラインで遊べます・進行状況はこの端末に保存" },
    menu: { start: "ゲーム開始", continue: "続きから", help: "遊び方", settings: "設定", home: "メインメニュー", noSave: "セーブデータなし", overwriteTitle: "新しい冒険を始めますか？", overwriteCopy: "新しいゲームを始めると現在の進行状況が上書きされます。続けますか？" },
    common: { backHome: "メイン画面へ", gameStatus: "ゲーム状況", mainMenu: "メイン画面", settings: "設定", language: "言語", board: "戦闘ボード", helpChapters: "説明の章", cancel: "キャンセル", confirm: "確認", close: "閉じる", yes: "はい、始めよう！", no: "まだやめておく", ok: "わかりました", gold: "ゴールド", active: "有効", inactive: "無効", locked: "ロック中", unlocked: "ロック解除" },
    game: {
      gold: "ゴールド", health: "体力", round: "ラウンド", level: "レベル", synergies: "シナジー", tipTitle: "ひとことヒント", boardEyebrow: "星明かりの戦場", boardTitle: "配置ボード", exp: "経験値", readyHint: "仲間を買い、仲間をクリックしてからマスをクリックして配置しましょう！", selectHint: "{name}を選択中 — 配置するマスを選んでください", boardFull: "現在のレベルではこれ以上配置できません。", boardCapacity: "出撃 {current} / {max}", boardTile: "ボードのマス {number}", placed: "{name}の準備完了！", removed: "{name}をベンチに戻しました", shop: "星明かりショップ", bench: "ベンチ", benchHint: "ベンチの仲間を選んでからボードのマスを選択", refresh: "更新", lock: "ロック", unlock: "解除", startBattle: "戦闘開始", buyXp: "経験値を買う", noGold: "ゴールドが足りません！", noUnits: "まず1体以上をボードに配置してください。", alreadyOut: "体力が0です。新しい冒険を始めてください。", lockedShop: "ショップはロック中です。", refreshed: "ショップを更新しました！", bought: "{name}を購入！", xpBought: "経験値を{amount}獲得", levelUp: "レベル{level}！配置上限が増えました！", placedAuto: "{name}がベンチに入りました", phase: { prepare: "準備", battle: "自動戦闘", settle: "結果発表" }, stage: "ウェーブ {round}", battleStarting: "チームを固定しました。戦闘を計算中…", battleVictory: "勝利！星の仲間たちが守り抜きました。", battleDefeat: "惜敗！次のラウンドで取り返せます。", battleDraw: "引き分け！両チームとも全力でした。", attackLog: "{attacker}が{target}に{damage}ダメージ", healLog: "{target}の体力が{amount}回復", shieldLog: "{target}が{amount}のシールドを得た", skillLog: "{attacker}が{skill}を発動！", defeatedLog: "{name}は倒れました", rewardLog: "収入 +{income}ゴールド（基本 {base}・利息 {interest}）", damageTaken: "{damage}ダメージを受けました", resultTitleWin: "勝利！", resultTitleLose: "もう一度！", resultTitleDraw: "すばらしい引き分け！", resultCopyWin: "あなたの編成が星空の下で輝いています。", resultCopyLose: "編成とシナジーを整えて、次の波に挑みましょう！", resultCopyDraw: "互角の戦いでした。次の対決に備えましょう。", survivors: "生存ユニット：{player} / {enemy}", resultDamage: "このラウンドの体力変化：{damage}", resultContinue: "次のラウンドへ", gameOverTitle: "冒険はいったん休憩", gameOverCopy: "{round}ラウンドを生き残りました。星々はこの旅を覚えています。", backToMenu: "メイン画面へ", tooLoud: "⚠️ 音量が大きすぎると音割れや不快感の原因になります。ご注意ください。", narrowHint: "ウィンドウを広げるか、スマホを縦向きにしてください。遊び続けることはできます。", tips: ["10ゴールドごとに利息1、最大5です。", "同じ仲間が3体集まると自動合成され、強くなります。", "シナジーはボード上の仲間で数えます。2体ボーナスも役立ちます。", "ショップをロックするとラウンド移行後も内容が残ります。", "メイジはマナが必要ですが、スキルで戦況を変えられます。"]
    },
    races: { forest: "森", flame: "炎", tide: "潮", sky: "空", crystal: "水晶" },
    classes: { guardian: "ガーディアン", striker: "ストライカー", mystic: "ミスティック", ranger: "レンジャー", mage: "メイジ" },
    units: { mossling: { name: "モスリング", ability: "モスシールド" }, emberfox: { name: "ほのおギツネ", ability: "ちいさな爆炎" }, tidepup: { name: "なみいぬ", ability: "潮のいやし" }, moonmoth: { name: "月のちょう", ability: "月影の矢" }, stoneback: { name: "いわガメ", ability: "大地の壁" }, cloudmage: { name: "くも魔法使い", ability: "雲の祝福" }, thornknight: { name: "いばら騎士", ability: "いばら返し" }, starseer: { name: "星読み", ability: "流星雨" }, sunlion: { name: "ひかりライオン", ability: "太陽の咆哮" }, crystaldragon: { name: "クリスタルドラゴン", ability: "虹晶の爆発" } },
    synergies: { forest: { name: "森のこころ", bonus: "全員の防御 +12%" }, flame: { name: "熱い火花", bonus: "全員の攻撃 +15%" }, tide: { name: "潮のこだま", bonus: "全員のマナ回復 +20%" }, sky: { name: "軽やかな翼", bonus: "全員の攻撃速度 +15%" }, crystal: { name: "水晶共鳴", bonus: "全員の体力 +18%" }, guardian: { name: "堅い守り", bonus: "ガーディアンの被ダメージ -15%" }, striker: { name: "前へ進め", bonus: "ストライカーの攻撃 +12%" }, mystic: { name: "秘術の光", bonus: "スキルダメージ +18%" }, ranger: { name: "遠星の狙い", bonus: "レンジャーの攻撃速度 +12%" }, mage: { name: "魔力の潮", bonus: "メイジの初期マナ +20" } },
    help: {
      eyebrow: "初心者ガイド", title: "遊び方", startNow: "今すぐ遊ぶ", chapters: { goal: "ゲームの目標", economy: "ゴールドと経済", shop: "ショップと購入", board: "配置操作", merge: "星の合成", synergy: "シナジー", battle: "戦闘ルール", result: "結果発表", faq: "よくある質問" },
      goal: { title: "星明かりを守り、最後のチームになろう！", intro: "仲間を買って配置し、自動戦闘で勝利を目指しましょう。", steps: [{ title: "ショップを見る", text: "コスト、種族、クラスを見て相性のよい組み合わせを探します。" }, { title: "チームを配置", text: "ベンチの仲間、次にマスを選択。前衛が攻撃を受け、後衛が攻撃します。" }, { title: "ウェーブを生き残る", text: "ラウンドごとに収入と体力が変わります。長く生きるほどスコアが上がります。" }], callout: "ヒント：ラウンド結果のたびに自動保存されます。" },
      economy: { title: "ゴールドで夢を育てよう", intro: "経済も戦いの一つ。利息を残しつつ、編成が遅れないよう投資しましょう。", steps: [{ title: "基本収入", text: "毎ラウンド5ゴールド。連勝ボーナスもあります。" }, { title: "利息", text: "所持10ゴールドごとに利息1、最大5ゴールドです。" }, { title: "経験値を買う", text: "4ゴールドで経験値を購入。レベルで配置数と高コスト出現率が上がります。" }], callout: "更新前に、次の利息ラインを残せるか確認しましょう。" },
      shop: { title: "星明かりの仲間を選ぶ", intro: "毎ラウンド5体の候補が登場。計画中はショップをロックできます。", steps: [{ title: "仲間を購入", text: "カードのゴールドボタンを押すとベンチに入ります。" }, { title: "更新", text: "2ゴールドで5体を入れ替えます。ロック中はラウンド移行でも変わりません。" }, { title: "コストを見る", text: "高コストはレア、低コストは合成しやすい。どちらも有効です。" }], callout: "カードの種族とクラスのタグがシナジーの手がかりです。" },
      board: { title: "2つの方法でかんたん配置", intro: "PCではドラッグ、スマホでは選択してからタップがおすすめです。", steps: [{ title: "選択", text: "ベンチの仲間をクリック。カードが光れば選択中です。" }, { title: "配置", text: "空いているマスをクリック。配置数はレベルで決まります。" }, { title: "調整", text: "配置済みの仲間をクリックするとベンチに戻せます。" }], callout: "操作ボタンはタッチしやすいサイズで、スマホではショップを横にスクロールできます。" },
      merge: { title: "3体が1つの星になる", intro: "同じ名前・同じ星の仲間を3体集めると自動合成されます。", steps: [{ title: "3体集める", text: "ボードとベンチの仲間を合わせて数えます。" }, { title: "自動合成", text: "費用は不要。星のエフェクトと音で知らせます。" }, { title: "さらに強く", text: "1、2、3星の能力係数は1.0、1.8、3.2です。" }], callout: "できるだけ配置中の仲間を残すので、前衛が急に消えることはありません。" },
      synergy: { title: "シナジーでチームが輝く", intro: "ボード上で種族やクラスの条件を満たすと全体ボーナスが発動します。", steps: [{ title: "タグを見る", text: "すべてのカードに種族とクラスが1つずつあります。" }, { title: "条件を満たす", text: "左パネルで現在数と次の発動条件を確認できます。" }, { title: "ボーナス発動", text: "戦闘前のスナップショットにボーナスが適用されます。" }], callout: "すべてを狙う必要はありません。1〜2個の中心シナジーが安定します。" },
      battle: { title: "一定のリズムで自動戦闘", intro: "戦闘開始後は操作できません。攻撃速度、標的、マナ、スキルで結果が決まります。", steps: [{ title: "行動tick", text: "0.1秒ごとにタイマーを確認し、準備できた仲間が行動します。" }, { title: "標的を選ぶ", text: "基本は最も近い敵。設定で最低体力を優先できます。" }, { title: "スキル", text: "攻撃と被弾でマナが増え、満タンになると自動発動します。" }], formula: "ダメージ = max(1, 攻撃力 × (1 − 防御力 ÷ (防御力 + 100)))", callout: "盤面のエフェクトは結果のリプレイ。勝敗はtick計算で決まっています。" },
      result: { title: "結果を次のラウンドの力に", intro: "結果により体力、ゴールド、連勝、セーブが更新されます。", steps: [{ title: "勝利", text: "体力を保ち、収入と連勝ボーナスを得ます。" }, { title: "敗北", text: "敵の生存数と星でダメージを受けますが、基本収入は得られます。" }, { title: "再び準備", text: "ラウンドが進みショップが更新。整えて再戦します。" }], callout: "体力が0になると冒険終了ですが、設定と最高ラウンドは残ります。" },
      faq: { title: "よくある質問", intro: "質問をクリックすると答えが開きます。", items: [{ q: "index.htmlを直接開けますか？", a: "はい。ビルドもCDNも不要なネイティブHTMLゲームなので、オフラインでも遊べます。" }, { q: "自動保存されますか？", a: "はい。ラウンド結果のたびにlocalStorageへ保存し、設定は別の保存領域を使います。" }, { q: "ショップを更新できないのはなぜ？", a: "更新には2ゴールド必要です。足りないときは収入を待ちましょう。" }, { q: "スマホでドラッグできますか？", a: "できますが、タッチ画面では選択してからタップする方法がおすすめです。PCではドラッグも対応します。" }, { q: "音量が100%を超えるのはなぜ？", a: "BGMは仕様上1000%まで対応しています。DynamicsCompressorNodeで音割れを抑えますが、大音量には注意してください。" }] }
    },
    settings: { eyebrow: "自分好みに設定", autoSave: "自動保存", reset: "初期設定に戻す", appearance: "外観", language: "言語", audio: "オーディオ", gameplay: "ゲーム設定", data: "データ管理", themeLabel: "好きな色の世界を選択", languageLabel: "すべてのページに即時反映", bgm: "BGM音量", sfx: "効果音音量", mute: "ミュート", muted: "ミュート中", soundOn: "サウンドON", battleSpeed: "戦闘アニメ速度", targetStrategy: "攻撃対象", nearest: "最も近い敵", lowest: "体力が低い敵", deleteTitle: "セーブを削除しますか？", deleteCopy: "ゲーム進行だけを削除し、言語・テーマ・音量設定は残ります。", deleteSave: "セーブを削除", resetTitle: "設定をすべて戻しますか？", resetCopy: "テーマ、言語、音量、戦闘設定が初期値になります。", resetDone: "設定を初期化しました", saved: "設定を自動保存しました", themes: { cute: "キュートピンク", ocean: "さわやかオーシャン", sunset: "あたたかい夕日", forest: "森のグリーン", galaxy: "夢のギャラクシー", dark: "やさしいダーク" }, languages: { "zh-TW": "繁體中文", en: "English", ja: "日本語" } },
    audio: { click: "クリック", buy: "購入", place: "配置", merge: "合成", victory: "勝利", defeat: "敗北" },
    toast: { saved: "進行状況を保存しました", cleared: "セーブを削除しました", audioReady: "オーディオを有効にしました" },
    errors: { generic: "少し問題が起きました。もう一度お試しください。" }
  };
}(window));
