(function (root) {
  root.AutoBattlerLang = root.AutoBattlerLang || {};
  root.AutoBattlerLang.en = {
    app: { title: "Starry Sprouts", tagline: "Plant a dream and let your friends battle!", offline: "Offline play ・ Progress stays on this device" },
    menu: { start: "Start Game", continue: "Continue", help: "How to Play", settings: "Settings", home: "Main menu", noSave: "No save found", overwriteTitle: "Start a new adventure?", overwriteCopy: "Starting a new game will replace your current progress. Continue?" },
    common: { backHome: "Back to Main Menu", gameStatus: "Game status", mainMenu: "Main menu", settings: "Settings", language: "Language", board: "Battle board", helpChapters: "Help chapters", cancel: "Cancel", confirm: "Confirm", close: "Close", yes: "Yes, let's go!", no: "Not yet", ok: "Got it", gold: "Gold", active: "Active", inactive: "Inactive", locked: "Locked", unlocked: "Unlocked" },
    game: {
      gold: "Gold", health: "Health", round: "Round", level: "Level", synergies: "Synergies", tipTitle: "Tiny tip", boardEyebrow: "Starry battlefield", boardTitle: "Formation board", exp: "EXP", readyHint: "Buy a friend, then click it and a board tile to form your team!", selectHint: "{name} selected — choose a board tile", boardFull: "Your current level has reached its board limit.", boardCapacity: "On board {current} / {max}", boardTile: "Board tile {number}", placed: "{name} is ready!", removed: "{name} returned to the bench", shop: "Starry shop", bench: "Bench", benchHint: "Select a benched friend, then choose a board tile", refresh: "Refresh", lock: "Lock", unlock: "Unlock", startBattle: "Start battle", buyXp: "Buy EXP", noGold: "Not enough gold!", noUnits: "Place at least one friend on the board.", alreadyOut: "Your health is empty. Start a new adventure.", lockedShop: "The shop is locked.", refreshed: "Shop refreshed!", bought: "Bought {name}!", xpBought: "Gained {amount} EXP", levelUp: "Reached level {level}! Board capacity increased!", placedAuto: "{name} joined the bench", phase: { prepare: "Preparation", battle: "Auto battle", settle: "Round result" }, stage: "Wave {round}", battleStarting: "Teams locked. Running the battle simulation…", battleVictory: "Victory! Your starry friends held the line.", battleDefeat: "Close one! You can recover next round.", battleDraw: "Draw! Both teams gave it everything.", attackLog: "{attacker} dealt {damage} damage to {target}", healLog: "{target} recovered {amount} health", shieldLog: "{target} gained {amount} shield", skillLog: "{attacker} cast {skill}!", defeatedLog: "{name} was defeated", rewardLog: "Income +{income} gold (base {base} ・ interest {interest})", damageTaken: "Took {damage} damage", resultTitleWin: "Victory!", resultTitleLose: "Keep going!", resultTitleDraw: "A beautiful draw!", resultCopyWin: "Your formation is glowing under the stars.", resultCopyLose: "Tune your formation and synergies — the next wave is yours.", resultCopyDraw: "A perfect stalemate. Get ready for the next duel.", survivors: "Survivors: {player} / {enemy}", resultDamage: "Health change this round: {damage}", resultContinue: "Continue to next round", gameOverTitle: "The adventure rests for now", gameOverCopy: "You survived {round} rounds. The stars will remember this journey.", backToMenu: "Return to main menu", tooLoud: "⚠️ Very loud audio may distort or feel uncomfortable. Please take care.", narrowHint: "Try a wider window or portrait phone view. You can still keep playing.", tips: ["Every 10 gold grants 1 interest, up to 5.", "Three matching friends merge automatically and become much stronger.", "Synergies count friends on the board; even a two-piece bonus helps.", "A locked shop keeps its current friends when the round changes.", "Mages need time to charge mana, but their spells can turn a battle around."]
    },
    races: { forest: "Forest", flame: "Flame", tide: "Tide", sky: "Sky", crystal: "Crystal" },
    classes: { guardian: "Guardian", striker: "Striker", mystic: "Mystic", ranger: "Ranger", mage: "Mage" },
    units: {
      mossling: { name: "Mossling", ability: "Moss Shield" }, emberfox: { name: "Ember Fox", ability: "Tiny Blaze" }, tidepup: { name: "Tide Pup", ability: "Tidal Mend" }, moonmoth: { name: "Moon Moth", ability: "Moonlit Arrow" }, stoneback: { name: "Stoneback", ability: "Earth Barrier" }, cloudmage: { name: "Cloud Mage", ability: "Cloud Blessing" }, thornknight: { name: "Thorn Knight", ability: "Thorn Counter" }, starseer: { name: "Star Seer", ability: "Meteor Shower" }, sunlion: { name: "Sun Lion", ability: "Solar Roar" }, crystaldragon: { name: "Crystal Dragon", ability: "Prismatic Burst" }
    },
    synergies: {
      forest: { name: "Heart of the Forest", bonus: "+12% team defense" }, flame: { name: "Hot Sparks", bonus: "+15% team attack" }, tide: { name: "Tidal Echo", bonus: "+20% team mana gain" }, sky: { name: "Light Wings", bonus: "+15% team attack speed" }, crystal: { name: "Crystal Resonance", bonus: "+18% team health" }, guardian: { name: "Steady Line", bonus: "Guardians take 15% less damage" }, striker: { name: "Charge Ahead", bonus: "+12% Striker attack" }, mystic: { name: "Arcane Gleam", bonus: "+18% spell damage" }, ranger: { name: "Far-Star Aim", bonus: "+12% Ranger attack speed" }, mage: { name: "Mana Tide", bonus: "+20 starting mana for Mages" }
    },
    help: {
      eyebrow: "New player guide", title: "How to Play", startNow: "Start playing now", chapters: { goal: "Goal", economy: "Gold & economy", shop: "Shop & buying", board: "Formation", merge: "Star merging", synergy: "Synergies", battle: "Battle rules", result: "Round results", faq: "FAQ" },
      goal: { title: "Protect the starlight and be the last team standing!", intro: "Buy the right friends, place them well, and let them fight automatically for your next victory.", steps: [{ title: "Read the shop", text: "Look at costs, races, and classes to find combinations that support each other." }, { title: "Form your team", text: "Select a benched friend, then a board tile. Frontliners take hits while the back row deals damage." }, { title: "Survive waves", text: "Every round updates your income and health. The longer you survive, the higher your score." }], callout: "Tip: the game auto-saves after every round result." },
      economy: { title: "Let your gold grow the dream", intro: "Economy is another battle. Keep enough gold for interest, but invest before your formation falls behind.", steps: [{ title: "Base income", text: "Gain 5 gold each round, plus possible win-streak rewards." }, { title: "Interest", text: "Every 10 gold held grants 1 interest, up to 5 gold." }, { title: "Buy experience", text: "Spend 4 gold for EXP. Levels increase board capacity and improve high-cost shop odds." }], callout: "A simple rule: check your next interest threshold before refreshing the shop." },
      shop: { title: "Choose your starry friends", intro: "The shop offers five candidates each round. Buy a friend you like, or lock the shop while you plan.", steps: [{ title: "Buy a friend", text: "Click the gold button on a card. The friend moves to your bench." }, { title: "Refresh", text: "Spend 2 gold for five new choices. A locked shop stays unchanged between rounds." }, { title: "Compare costs", text: "High-cost friends are rare, while low-cost friends merge more easily. Both paths work." }], callout: "Race and class tags on each card are clues for building synergies." },
      board: { title: "Two easy ways to form a team", intro: "Drag on desktop, or select then tap on mobile to avoid accidental moves.", steps: [{ title: "Select", text: "Click a benched friend. A highlighted card means it is selected." }, { title: "Place", text: "Click an empty tile to deploy the friend. Capacity is set by your level." }, { title: "Adjust", text: "Click a deployed friend to return it to the bench, then try a new position." }], callout: "Every interactive control keeps a comfortable touch target, and the shop scrolls horizontally on phones." },
      merge: { title: "Three become one brilliant star", intro: "Collect three matching friends with the same star level and they merge automatically.", steps: [{ title: "Collect three", text: "Friends on the board and bench are counted together." }, { title: "Auto merge", text: "Merging costs nothing and shows a star-up effect and sound." }, { title: "Break through", text: "The power coefficients for 1, 2, and 3 stars are 1.0, 1.8, and 3.2." }], callout: "A deployed friend is kept when possible, so your frontline does not suddenly vanish." },
      synergy: { title: "Synergies make the team shine", intro: "Reach a race or class threshold on the board to activate a team bonus.", steps: [{ title: "Read tags", text: "Every card shows one race and one class." }, { title: "Reach a threshold", text: "The left panel shows current counts and the next activation threshold." }, { title: "Enjoy the bonus", text: "Bonuses are applied to combat snapshots before the battle starts." }], callout: "You do not need every synergy. One or two focused core bonuses are often stronger." },
      battle: { title: "Auto battle with a steady rhythm", intro: "After battle starts you cannot intervene. Attack speed, target strategy, mana, and spells decide the result.", steps: [{ title: "Action ticks", text: "Every 0.1 seconds, attack timers are checked and ready friends act." }, { title: "Pick a target", text: "The default target is the nearest enemy. Settings can prioritize the lowest health." }, { title: "Spell burst", text: "Attacks and damage build mana. A full mana bar triggers the skill automatically." }], formula: "Damage = max(1, attack × (1 − defense ÷ (defense + 100)))", callout: "The board effects are a friendly replay; the tick simulation already decided the result." },
      result: { title: "Every result powers the next round", intro: "The result updates health, gold, streaks, and your local save.", steps: [{ title: "Win", text: "Keep your health and earn income plus possible win-streak rewards." }, { title: "Lose", text: "Take damage based on enemy survivors and stars, but still receive base income." }, { title: "Prepare again", text: "The round advances and the shop updates. Rebuild, then start another battle." }], callout: "Zero health ends the adventure, but settings and your best round are kept." },
      faq: { title: "Frequently asked questions", intro: "Tap a question to reveal a friendly answer.", items: [{ q: "Can I double-click index.html?", a: "Yes. This is a native HTML game with no build step or CDN dependency, so it also works offline." }, { q: "Does the game save automatically?", a: "Yes. The game state is saved to localStorage after each round result. Settings use a separate save." }, { q: "Why cannot I refresh the shop?", a: "One refresh costs 2 gold. If you are short, keep your economy and wait for the next income." }, { q: "Can I drag on a phone?", a: "Yes, but select-then-tap is recommended on touch screens. Desktop supports dragging too." }, { q: "Why can volume exceed 100%?", a: "The spec allows BGM up to 1000%. A DynamicsCompressorNode helps prevent clipping, but loud levels still need care." }] }
    },
    settings: { eyebrow: "Personalize your game", autoSave: "Auto-saved", reset: "Restore defaults", appearance: "Appearance", language: "Language", audio: "Audio", gameplay: "Gameplay", data: "Data management", themeLabel: "Choose your color world", languageLabel: "Every page updates instantly", bgm: "BGM volume", sfx: "SFX volume", mute: "Mute", muted: "Muted", soundOn: "Sound on", battleSpeed: "Battle animation speed", targetStrategy: "Target strategy", nearest: "Nearest first", lowest: "Lowest health first", deleteTitle: "Delete the game save?", deleteCopy: "Only game progress will be deleted; language, theme, and volume settings stay safe.", deleteSave: "Delete save", resetTitle: "Restore all settings?", resetCopy: "Theme, language, volume, and battle preferences return to their defaults.", resetDone: "Settings restored", saved: "Settings auto-saved", themes: { cute: "Cute pink", ocean: "Fresh ocean", sunset: "Warm sunset", forest: "Forest green", galaxy: "Dream galaxy", dark: "Comfort dark" }, languages: { "zh-TW": "繁體中文", en: "English", ja: "日本語" } },
    audio: { click: "Button click", buy: "Buy", place: "Place", merge: "Merge", victory: "Victory", defeat: "Defeat" },
    toast: { saved: "Progress saved", cleared: "Game save deleted", audioReady: "Audio enabled" },
    errors: { generic: "Something went a little wrong. Please try again." }
  };
  root.AutoBattlerLang.en.game.levelExp = "Level EXP";
  root.AutoBattlerLang.en.game.buyXp = "Buy card EXP";
  root.AutoBattlerLang.en.game.xpBought = "All owned friends gained {amount} EXP";
  root.AutoBattlerLang.en.game.unitXp = "{name} consumed a duplicate for +{amount} EXP";
  root.AutoBattlerLang.en.game.starUp = "{name} reached {star} stars!";
  root.AutoBattlerLang.en.game.tips[1] = "Matching friends feed each other for EXP regardless of star, up to 5 stars.";
  root.AutoBattlerLang.en.help.merge = {
    title: "Feed duplicates, reach five stars",
    intro: "Friends with the same name can consume one another regardless of their current star.",
    steps: [
      { title: "Match the name", text: "The board and bench are counted together, and the stars do not need to match." },
      { title: "Fill EXP", text: "Each consumed duplicate grants 1 card EXP. A full bar immediately raises the star." },
      { title: "Reach five stars", text: "The power coefficients for 1–5 stars are 1.0, 1.8, 3.2, 4.8, and 6.8." }
    ],
    callout: "Buying card EXP raises the experience of every friend you own."
  };
  root.AutoBattlerLang.en.help.economy = {
    title: "Let your gold grow the dream",
    intro: "Economy is another battle. Keep enough gold for interest, then invest in the friends you own.",
    steps: [
      { title: "Base income", text: "Gain 5 gold each round, plus possible win-streak rewards." },
      { title: "Interest", text: "Every 10 gold held grants 1 interest, up to 5 gold." },
      { title: "Buy card EXP", text: "Spend 4 gold to grant 4 EXP to every owned friend; player level still grows from round results." }
    ],
    callout: "Check your next interest threshold before refreshing the shop."
  };
}(window));
